### ISSUE TITLE
Coordinates Editor

### ISSUE THREAD

**Issue by agriffard** [ThisNetWorks/ThisNetWorks.OrchardCore.GoogleMaps#6]
Do you plan to provide another way to set the latitude or the longitude?
It would be easier if we were able to drag and drop a pin or search for an address and set the position.

For the default location, the page could also ask to access the browser geolocation and set the location to it.

**Comment by deanmarcussen** [comment]
Currently it uses Google Places to search for an address ( you have to enable places on the api )

You can set the default location in the setting for it (I didn't use the browser geo, as often the sites are being developed in a different area to the users)

I need to add a feature for a more defined location (i.e. not pin based), but surrounding a geo area fence
