### ISSUE TITLE
Map not loaded until refresh in the blog post

### ISSUE THREAD

**Issue by vitalybrandes** [ThisNetWorks/ThisNetWorks.OrchardCore.GoogleMaps#7]
Hi @deanmarcussen , cool module, thanks!!!
The multiple marker map is ok, but once enter the post, map not shown only if refresh page (F5) map shown.
This is console error:
![image](https://user-images.githubusercontent.com/61165619/88256588-6518c580-ccc4-11ea-8630-7758bf6eb9ef.png)

**Comment by deanmarcussen** [comment]
No worries, is this on the sample or when you have used it yourself?

I'll need a bit more detail.

It sounds like a script ordering error?

**Comment by vitalybrandes** [comment]
> 
> 
> No worries, is this on the sample or when you have used it yourself?
> 
> I'll need a bit more detail.
> 
> It sounds like a script ordering error?

@deanmarcussen 
I copy the module and Liquid files to my own tester.
Running it as blog recipe.

In same question, i am not familiar with liquid, can you tell me how to add the map / maps in to for CSHTML file?
