### ISSUE TITLE
How to call shape in Razor pages?

### ISSUE THREAD

**Issue by vitalybrandes** [ThisNetWorks/ThisNetWorks.OrchardCore.GoogleMaps#8]
Hi,
how can i call the shapes of multiple markers and single marker in razor pages?
What i am doing wrong?
![image](https://user-images.githubusercontent.com/61165619/88515449-631c7280-cff4-11ea-8b79-8d6f95b3f951.png)

**Comment by deanmarcussen** [comment]
Maybe you are confusing shapes with content items?

I would imagine you want to call `@await DisplayAsync(Model.Content.Named("GoogleMapPart"))` to render the actual shape.

`Model.CompanyName` looks like something else

**Comment by deanmarcussen** [comment]
Closing as no response
